### ISSUE TITLE
Bug: Empty string to Expression causes IndexError

### ISSUE THREAD

**Issue by bwrsandman** [glenfletcher/Equation#25]
## Description

There is a bug possible for APIs using Equation when they feed an empty string to Expression. This is an edge case, but it still something a strong API should guard against.
### How to reproduce

``` python
from Equation import Expression

Expression("")
```
### Expected behaviour

Return 0, or throw a helpful error message saying the string was empty
### Actual behaviour

API crashes with an IndexError:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/Equation/core.py", line 405, in __repr__
    return args[0]
IndexError: list index out of range
```

**Comment by glenfletcher** [comment]
Fixed in Bug-Fix#25, Now Returns Empty String from repr, and str for an empty equation.

**Comment by bwrsandman** [comment]
How about when it is called?

That seems to be still broken.

```
>>> from Equation import Expression
>>> Expression("")  

>>> Expression("")()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/Equation/Equation/core.py", line 302, in __call__
    return args[0]
IndexError: list index out of range

```
